development:
  adapter: postgresql
  encoding: unicode
  database: main-dev
  pool: 5
  host: localhost
  username: jetskee96
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: main-test
  pool: 5
  host: localhost
  username: jetskee96
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: main-prod
  pool: 5
  host: localhost
  username: jetskee96
  password: